In [1]:
# Import necessary packages
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score
from sklearn.metrics import classification_report, confusion_matrix

# Neural Networks
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

In [2]:
df = pd.read_csv('../../Data/zoo.data.csv', header = 0)

In [4]:
df.columns=['Name','hair','feathers','eggs','milk','airborne','aquatic', 'predator', 'toothed','backbone','breathes','venomous','fins','legs','tail','domestic','catsize','type']

In [5]:
# Print the first few rows
df.head()

,Name,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,type
0,antelope,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1,1
1,bass,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0,4
2,bear,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
3,boar,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1
4,buffalo,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1,1

In [6]:
# Print dataset shape 

print(df.shape)
df.describe().T
# Describe dataset

(100, 18)

          count  mean       std  min   25%  50%  75%  max
hair      100.0  0.42  0.496045  0.0  0.00  0.0  1.0  1.0
feathers  100.0  0.20  0.402015  0.0  0.00  0.0  0.0  1.0
eggs      100.0  0.59  0.494311  0.0  0.00  1.0  1.0  1.0
milk      100.0  0.40  0.492366  0.0  0.00  0.0  1.0  1.0
airborne  100.0  0.24  0.429235  0.0  0.00  0.0  0.0  1.0
aquatic   100.0  0.36  0.482418  0.0  0.00  0.0  1.0  1.0
predator  100.0  0.55  0.500000  0.0  0.00  1.0  1.0  1.0
toothed   100.0  0.60  0.492366  0.0  0.00  1.0  1.0  1.0
backbone  100.0  0.82  0.386123  0.0  1.00  1.0  1.0  1.0
breathes  100.0  0.79  0.409360  0.0  1.00  1.0  1.0  1.0
venomous  100.0  0.08  0.272660  0.0  0.00  0.0  0.0  1.0
fins      100.0  0.17  0.377525  0.0  0.00  0.0  0.0  1.0
legs      100.0  2.83  2.040276  0.0  2.00  3.0  4.0  8.0
tail      100.0  0.75  0.435194  0.0  0.75  1.0  1.0  1.0
domestic  100.0  0.13  0.337998  0.0  0.00  0.0  0.0  1.0
catsize   100.0  0.43  0.497570  0.0  0.00  0.0  1.0  1.0
type      100.0  2.85  2.105188  1.0  1.00  2.0  4.0  7.0

In [9]:
# Create feature and target arrays, save as X and y
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [10]:
# One hot encode labels
from sklearn.preprocessing import OneHotEncoder 

encoded_X = OneHotEncoder().fit_transform(X).toarray()
print(encoded_X)

[[1. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]

In [11]:
# Split into Training & Testing Sets
X_train, X_test, y_train, y_test = train_test_split(encoded_X, y, test_size=0.30, random_state=123)

In [12]:
# Print feature data 
print(X_train.shape)
print(X_test.shape)

(70, 135)
(30, 135)

In [13]:
# Create Clasifier Object

mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='relu', solver='adam', max_iter=250)

In [14]:
# Fit Classifier
mlp.fit(X_train , y_train)

C:\Users\hmamo\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(

MLPClassifier(hidden_layer_sizes=(8, 8, 8), max_iter=250)

In [15]:
# Make Predictions

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [16]:
# Print metrics
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[29  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0]
 [ 0  0  4  0  0  0  0]
 [ 0  0  0  9  0  0  0]
 [ 0  0  1  1  0  0  0]
 [ 0  0  0  0  0  0  3]
 [ 0  0  0  0  0  0  9]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        29
           2       1.00      1.00      1.00        14
           3       0.80      1.00      0.89         4
           4       0.90      1.00      0.95         9
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         3
           7       0.75      1.00      0.86         9

    accuracy                           0.93        70
   macro avg       0.64      0.71      0.67        70
weighted avg       0.87      0.93      0.90        70

C:\Users\hmamo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hmamo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hmamo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))